#!/bin/bash
# Ensure service will be kept disabled accross system updates

systemctl disable dropbear.socket
mkdir -p /etc/systemd/system-preset
ln -s /dev/null /etc/systemd/system-preset/98-dropbear.preset
