#!/bin/sh

CPU_FREQUENCIES="200 400 600 1200 1600"

if ! echo " $CPU_FREQUENCIES " | grep -q " $1 "; then
    echo "Error: Invalid min frequency. Must be one of: $CPU_FREQUENCIES"
    exit 1
fi

if ! echo " $CPU_FREQUENCIES " | grep -q " $2 "; then
    echo "Error: Invalid max frequency. Must be one of: $CPU_FREQUENCIES"
    exit 1
fi

echo "Min $1MHz, max $2MHz"
for i in /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor; do echo "powersave" | sudo tee $i; done
for i in /sys/devices/system/cpu/cpu*/cpufreq/scaling_min_freq; do echo "${1}000" | sudo tee $i; done
for i in /sys/devices/system/cpu/cpu*/cpufreq/scaling_max_freq; do echo "${2}000" | sudo tee $i; done
