#!/bin/sh

PID=0061
VID=2341
BOARDNAME=PortentaM8
BOARDPROVIDER=Arduino
UDC=ci_hdrc.0       
cd /sys/kernel/config/usb_gadget/
mkdir g1                         
cd g1   
echo 0x$VID > idVendor
echo 0x$PID > idProduct
mkdir strings/0x409    
echo 012345678 > strings/0x409/serialnumber
echo $BOARDPROVIDER > strings/0x409/manufacturer
echo $BOARDNAME > strings/0x409/product         
mkdir functions/acm.GS0                
mkdir functions/ffs.adb
mkdir configs/c.1      
mkdir configs/c.1/strings/0x409
echo \"adb+cdc\" > configs/c.1/strings/0x409/configuration
echo 120 > configs/c.1/MaxPower                           
ln -s functions/acm.GS0 configs/c.1
ln -s functions/ffs.adb/ configs/c.1
mkdir /dev/usb-ffs                  
mkdir /dev/usb-ffs/adb
mount -t functionfs adb /dev/usb-ffs/adb
adbd &                                  
sleep 2
ls /sys/class/udc
echo $UDC > UDC
