#!/bin/sh

if [[ $(cat /sys/class/typec/port0/data_role) == "[device]" ]]; then
    PID=0061
    VID=2341
    BOARDNAME="Portenta X8"
    BOARDPROVIDER="Arduino"
    cd /sys/kernel/config/usb_gadget/
    mkdir g1
    cd g1
    echo 0x$VID > idVendor
    echo 0x$PID > idProduct
    echo 0xEF > bDeviceClass
    echo 0x02 > bDeviceSubClass
    echo 0x01 > bDeviceProtocol
    mkdir strings/0x409
    echo $(cat /sys/devices/soc0/serial_number) > strings/0x409/serialnumber
    echo "$BOARDPROVIDER" > strings/0x409/manufacturer
    echo "$BOARDNAME" > strings/0x409/product
    echo 1       > os_desc/use
    echo 0xcd    > os_desc/b_vendor_code
    echo MSFT100 > os_desc/qw_sign
    mkdir functions/acm.GS0
    mkdir functions/ffs.adb
    mkdir functions/rndis.usb0
    echo RNDIS   > functions/rndis.usb0/os_desc/interface.rndis/compatible_id
    echo 5162001 > functions/rndis.usb0/os_desc/interface.rndis/sub_compatible_id
    mkdir configs/c.1
    mkdir configs/c.1/strings/0x409
    echo \"adb+cdc\" > configs/c.1/strings/0x409/configuration
    echo 120 > configs/c.1/MaxPower
    ln -s functions/rndis.usb0/ configs/c.1
    ln -s functions/acm.GS0 configs/c.1
    ln -s functions/ffs.adb/ configs/c.1
    ln -s configs/c.1 os_desc
    mkdir /dev/usb-ffs
    mkdir /dev/usb-ffs/adb
    mount -o uid=1000,gid=1000 -t functionfs adb /dev/usb-ffs/adb
    exit 0
else
    exit 1
fi
